### ISSUE TITLE
ExecutionContext is not returning names

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-csharp-lib#1]
Objective:
Get Specs and Scenario names during run time

Expected:
Below code should return names
ExecutionContext ec = new ExecutionContext();
string scname = ec.CurrentScenario.Name;
string spname = ec.CurrentSpecification.Name;
string stname = ec.CurrentStep.Text;

Actual:
Above code is returning empty values into corresponding variables

Steps:
1. Go to the step where you want to fetch names
2. Use below code to fetch names
ExecutionContext ec = new ExecutionContext();
string scname = ec.CurrentScenario.Name;
string spname = ec.CurrentSpecification.Name;
string stname = ec.CurrentStep.Text;

**Comment by zabil** [comment]
Fields/Variables in `ExecutionContext` is are available only in hooks. It cannot be initialised and used on its own. 

Here's documentation on how to use it as a parameter `BeforeScenario` and `AfterSpec` https://docs.gauge.org/latest/writing-specifications.html#current-execution-context-in-the-hook

**Comment by benquinteros** [comment]
any plans to expose this?
