### ISSUE TITLE
Readme documentation issue 

### ISSUE THREAD

**Issue by mstumpf585** [getgauge/gauge-csharp-lib#20]
The README states : "You will need Gauge and Gauge-csharp plugin installed before installing Lib" There doesn't seem to be a Gauge-csharp plugin in the VSCode Market place nor is there a Visual Studio extension. Is this referring to https://github.com/getgauge/gauge-csharp which is Deprecated? Does the README need updated to remove the reference to Gauge-charsp?

**Comment by zabil** [comment]
Yes that's right csharp is deprecated. Please feel free to send a pull request to remove references.

**Comment by mstumpf585** [comment]
So gauge-csharp-lib is no longer using the gauge plugin "csharp" it is just using "dotnet"? So I can remove this plugin from my environment? 

PS C:\Users\320022098\WorkSpace\GitWorkspace\otto> gauge version
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
csharp (0.10.6)
dotnet (0.1.8)
html-report (4.0.12)
python (0.3.11)
screenshot (0.0.1)
xml-report (0.2.3)
PS C:\Users\320022098\WorkSpace\GitWorkspace\otto>

**Comment by mstumpf585** [comment]
https://github.com/getgauge/gauge-csharp-lib/pull/21

**Comment by zabil** [comment]
> So gauge-csharp-lib is no longer using the gauge plugin "csharp" it is just using "dotnet"? So I can remove this plugin from my environment?

Yes. You can remove the plugin.
