### ISSUE TITLE
.Net SDK 8.0 support for nuget build

### ISSUE THREAD

**Issue by PiotrNestor** [getgauge/gauge-csharp-lib#40]
The Nuget build requires up to .Net SDK 8.0 support
https://github.com/getgauge/gauge-csharp-lib/actions/runs/7916134938

@zabil @sriv

**Comment by sriv** [comment]
this should be sorted. Gauge.CSharp.Lib 0.10.0 is released on nuget now - https://www.nuget.org/packages/Gauge.CSharp.Lib/
