### ISSUE TITLE
license

### ISSUE THREAD

**Issue by CosminSontu** [getgauge/gauge-csharp-lib#9]
Hi,

Does it make sense for this to be licensed as GPL v3? Wouldn't LGPL v3 be more appropriate?

Thanks

**Comment by sriv** [comment]
Hi,

Actually, we are in the process of moving everything to Apache 2.0. Some repos are done, rest will be done soon.

How does that sound?

Thanks for bringing this up.

**Comment by CosminSontu** [comment]
Sounds good.
Thanks!
